# Generated by Django 3.0.4 on 2020-04-12 22:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedDemoItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsfeedDemoTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsfeedDemoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('feed_key', models.CharField(max_length=32)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('main_image', models.URLField(blank=True, null=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.NewsfeedDemoItemType')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.NewsfeedDemoTopic')),
            ],
        ),
    ]
