# Generated by Django 3.0.4 on 2020-04-13 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsfeeddemoitem_newsfeeddemoitemtype_newsfeeddemotopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedDemoBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='newsfeeddemoitem',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.NewsfeedDemoBill'),
        ),
    ]
